author: Terra Firma Design & Consulting
summary: Plugin to interact with MailChimp email service.
homepage: http://svn.terra-firma-design.com/plugins/acts_as_mailchimp
plugin: http://svn.terra-firma-design/plugins/acts_as_mailchimp
license: MIT
version: 0.1a
rails_version: 2.0.1+