author: Terra Firma Design & Consulting
summary: Plugin to interact with MailChimp email service.
homepage: http://www.terra-firma-design.com
plugin: git://github.com/bgetting/acts_as_mailchimp.git
license: MIT
version: 0.1a
rails_version: 2.0.1+